name: Matrix Lab
on: workflow_dispatch
jobs:
  build:
    strategy:
      matrix:
        python: ['3.10', '3.11', '3.12']
      fail-fast: false  # important: lets others continue
      max-parallel: 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - run: python --version
      - run: echo "This is matrix job for Python ${{ matrix.python }}"
